#!/usr/bin/env bash
# This script redirecting to another page
#!/usr/bin/env bash
# Install Nginx in my server
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/ a \\tlocation = /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;\n\t}' /etc/nginx/sites-available/default
service nginx start
