#!/usr/bin/env bash
# This script redirecting to another page
#!/usr/bin/env bash
# Install Nginx in my server
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx start
sed -i '/server_name _;/ a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
