#!/usr/bin/env bash
# This script redirecting to another page
# Install Nginx in my server
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
# Redic 301
sed -i '/listen 80 default_server/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# error page config 404
echo "Ceci n'est pas une page" > /var/www/html/page404.html
sed -i "/server_name _;/ a\\\terror_page 404 \/page404.html;\n\tlocation = \/page404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
# Add header response
sed -i "/location \/ {/ a\\\t\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
# restarts the server
service nginx restart
