#!/usr/bin/env bash
# dispaly infinit create file, display mesagge if there is SIGTERM and SIGINT o SIGQUIT
echo $$ > /var/run/holbertonscript.pid
i=0
while [ $i ]
do
    trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM SIGQUIT
    trap 'echo "Y U no love me?!"' SIGINT
    echo "To infinity and beyond"
    ((i++))
done