#!/usr/bin/env bash
i=1

while [ $i -le 20 ]
do
    case $i in
        5)
            echo "bad luck from china"
            ;;

        10)
            echo "bad luck from japan"
            ;;
        18)
            echo "bad luck from italy"
            ;;
    esac
    echo "$i"
    ((i++))
done
