#!/usr/bin/env bash
# This script is displaying "bad luck from" any countrys
i=1

while [ $i -le 20 ]
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from china"
            ;;

        9)
            echo "$i"
            echo "bad luck from japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done
