#!/usr/bin/env bash
# This script display Hour and minutes
hours=0
minutes=1

while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        ((minutes++))
        done
    ((hours++))
done
